import {
  BedIcon,
  BooksIcon,
  BrainIcon,
  BuildingsIcon,
  BusIcon,
  ChatsCircleIcon,
  CurrencyInrIcon,
  DatabaseIcon,
  DeviceMobileIcon,
  GearSixIcon,
  GraduationCapIcon,
  IdentificationBadgeIcon,
  IdentificationCardIcon,
  PackageIcon,
  PaletteIcon,
  PlugsConnectedIcon,
  type Icon,
} from '@phosphor-icons/react'

// Keyed by module slug from navigation.ts; each glyph names what the module manages.
export const moduleIcons: Record<string, Icon> = {
  'core-setup-and-administration': BuildingsIcon,
  'academic-management': GraduationCapIcon,
  'student-information': GraduationCapIcon,
  'library-and-learning': BooksIcon,
  'fees-and-finance': CurrencyInrIcon,
  communication: ChatsCircleIcon,
  'hr-and-staff-management': IdentificationBadgeIcon,
  'id-cards': IdentificationCardIcon,
  'transport-management': BusIcon,
  'inventory-and-assets': PackageIcon,
  'hostel-dormitory': BedIcon,
  'mobile-apps-and-portals': DeviceMobileIcon,
  'ai-tools': BrainIcon,
  'integrations-and-technical': PlugsConnectedIcon,
  'settings-and-billing': GearSixIcon,
  'template-gallery': PaletteIcon,
  'backup-management': DatabaseIcon,
}
